apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: greeter-service
spec:
  hosts:
  - greeter-service
  http:
  - route:
    - destination:
        host: greeter-service
        subset: v1
      weight: 70
    - destination:
        host: greeter-service
        subset: v3
      weight: 30

